# Code generated by Gemini

import os
import argparse
import struct
import shutil

def optimize_with_layouts(chunk_files, layout_files, output_main):
    chunk_size = 0x80  # $80 bytes per chunk
    layout_offset = 0x88  # Data starts after level header

    if len(chunk_files) != len(layout_files):
        print("Error: The number of chunk files and layout files must match!")
        return

    # 1. Loading data and creating backups
    all_acts_chunks = []
    for f_name in chunk_files + layout_files:
        if os.path.exists(f_name):
            shutil.copy(f_name, f_name + ".bak")

    for f in chunk_files:
        with open(f, 'rb') as rb:
            data = rb.read()
            # Split binary data into list of 128-byte chunks
            chunks = [data[i:i + chunk_size] for i in range(0, len(data), chunk_size)]
            all_acts_chunks.append(chunks)

    # 2. Find common chunks (Intersection)
    # Maintain the order of appearance from the first input file
    first_act_chunks = all_acts_chunks[0]
    common_set = set(first_act_chunks)
    for act in all_acts_chunks[1:]:
        common_set &= set(act)

    common_chunks = []
    for c in first_act_chunks:
        if c in common_set and c not in common_chunks:
            common_chunks.append(c)

    num_common = len(common_chunks)
    print(f"--- Analysis Results ---")
    print(f"Common chunks found: {num_common} (ID 0x0000 - {hex(num_common-1)})")

    # 3. Process each act and patch Layouts
    new_act_chunks_list = []

    for act_idx, original_chunks in enumerate(all_acts_chunks):
        mapping = {} # Old ID -> New ID
        unique_chunks = []

        # Build the remapping table
        for old_id, chunk in enumerate(original_chunks):
            if chunk in common_set:
                # Common chunks go to the beginning (0...N)
                new_id = common_chunks.index(chunk)
                mapping[old_id] = new_id
            else:
                # Unique chunks go right after the common ones
                if chunk not in unique_chunks:
                    unique_chunks.append(chunk)

                new_id = num_common + unique_chunks.index(chunk)
                mapping[old_id] = new_id

        # 4. Patch Layout file (2-byte Word, Big-Endian)
        layout_path = layout_files[act_idx]
        if os.path.exists(layout_path):
            with open(layout_path, 'rb+') as f:
                f.seek(0, os.SEEK_END)
                f_size = f.tell()

                if f_size > layout_offset:
                    f.seek(layout_offset)
                    data_to_patch = f.read()
                    patched_layout = bytearray()

                    # Process 2 bytes at a time (Word)
                    for i in range(0, len(data_to_patch), 2):
                        if i + 1 < len(data_to_patch):
                            # Unpack Big-Endian Word
                            old_val = struct.unpack('>H', data_to_patch[i:i+2])[0]
                            # Replace if ID exists in mapping, otherwise keep (e.g. $FFFF)
                            new_val = mapping.get(old_val, old_val)
                            # Pack back as Big-Endian Word
                            patched_layout += struct.pack('>H', new_val)
                        else:
                            # Handle odd byte at the end if exists
                            patched_layout.append(data_to_patch[i])

                    f.seek(layout_offset)
                    f.write(patched_layout)
                    print(f"Layout '{layout_path}': Patched successfully.")

        new_act_chunks_list.append(unique_chunks)

    # 5. Save final binary files
    with open(output_main, 'wb') as f:
        for c in common_chunks:
            f.write(c)
    print(f"Main chunks file created: {output_main}")

    for i, file_name in enumerate(chunk_files):
        with open(file_name, 'wb') as f:
            for c in new_act_chunks_list[i]:
                f.write(c)
        print(f"Updated '{file_name}': {len(new_act_chunks_list[i])} unique chunks remaining.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Chunk Optimizer")
    parser.add_argument('--chunks', nargs='+', required=True, help='Space-separated list of chunk files')
    parser.add_argument('--layouts', nargs='+', required=True, help='Space-separated list of layout files')
    parser.add_argument('-o', '--output', default='ChunksMain.unc', help='Output main file name (default: ChunksMain.unc)')

    args = parser.parse_args()
    optimize_with_layouts(args.chunks, args.layouts, args.output)
