# Code generated by ChatGPT

first_value = int(input("Enter the first value: "), 16)

second_value = int(input("Enter the second value: "), 16)

percentage = (second_value / first_value) * 100

print(f"{second_value} is {percentage:.10f}% of the {first_value}")