# Code generated by LLaMA

# Get the first value from the console
first_value = int(input("Enter the first value: "), 16)

# Get the second value from the console
second_value = int(input("Enter the second value: "), 16)

# Calculate the percentage
percent = (second_value / first_value) * 100

# Print the result
print(f"{second_value} is {percent:.10f}% of the {first_value}")