# Code generated by Gemini

import sys

def collision_data_converter():
    # Table from Touch_Sizes (Width, Height in real pixels)
    touch_sizes_raw = [
        (8, 8), (40, 40), (24, 40), (40, 24), (8, 32), (24, 36), (32, 32), (12, 12),
        (48, 24), (24, 32), (32, 16), (16, 16), (40, 32), (40, 16), (28, 28), (48, 48),
        (80, 32), (32, 48), (16, 32), (64, 224), (128, 64), (256, 64), (64, 64), (16, 16),
        (8, 8), (64, 16), (24, 24), (16, 8), (48, 8), (80, 8), (8, 16), (8, 48),
        (8, 80), (48, 48), (48, 48), (24, 48), (144, 16), (48, 80), (32, 8), (64, 4),
        (32, 56), (24, 72), (32, 4), (8, 128), (48, 128), (64, 32), (56, 40), (32, 4),
        (32, 2), (4, 16), (32, 128), (24, 8), (16, 24), (80, 64), (128, 4), (192, 4), (80, 80)
    ]

    print("--- SCE Collision Data Converter ---")
    print("Enter HEX byte (e.g. 46, 98, E1):")
    
    while True:
        try:
            line = input("> ")
            if not line: continue
            val = int(line.replace('$', '').replace('0x', ''), 16)
            
            type_bits = val & 0xC0
            size_idx = val & 0x3F

            # Validation for Item range $40-$7F
            if type_bits == 0x40:
                if val == 0x47:
                    c_type = "collision_type.npc.ring"
                elif val == 0x46:
                    c_type = "collision_type.npc.monitor"
                else:
                    print(f"Error: Collision ${hex(val).upper()[2:]} does not exist (Item index)")
                    continue
            else:
                # Standard mapping for other ranges
                mapping = {
                    0x00: "collision_type.npc.touch",
                    0x80: "collision_type.npc.hurt",
                    0xC0: "collision_type.npc.double"
                }
                c_type = mapping.get(type_bits, "collision_type.npc.none")

            if size_idx < len(touch_sizes_raw):
                w, h = touch_sizes_raw[size_idx]
                print(f"\n; Input: ${hex(val).upper()[2:]}")
                print(f"\tmove.b\t#{c_type},collision_type(a0)")
                print(f"\tmove.b\t#{w}/2,collision_width(a0)")
                print(f"\tmove.b\t#{h}/2,collision_height(a0)\n")
            else:
                print(f"! Size index ${hex(size_idx).upper()[2:]} out of range")
                
        except ValueError:
            print("Error: Input must be a valid HEX byte")
        except KeyboardInterrupt:
            print("\nConverter closed.")
            sys.exit()

if __name__ == "__main__":
    collision_data_converter()
