# Code generated by ChatGPT

import re

# Input and output files
INPUT_FILE = "Kosinski Plus Module Data.asm"
OUTPUT_FILE = "output.asm"

# Regex pattern:
# 1) Label before ':'
# 2) include type (binclude / bincludeEntry / include)
# 3) Path inside quotes
pattern = re.compile(r'^(\w+):\s*(bincludeEntry|binclude|include)\s+"([^"]+)"')

# Mapping of include type -> suffix
suffix_map = {
    "binclude": "b",
    "bincludeEntry": "be",
    "include": "i",
}

converted_lines = []

with open(INPUT_FILE, "r", encoding="utf-8") as f:
    for line in f:
        line = line.rstrip()
        match = pattern.match(line)
        if match:
            label, inc_type, path = match.groups()
            suffix = suffix_map.get(inc_type, "i")  # fallback just in case
            new_line = f'\t\tincfile.{suffix}\t{label}, "{path}"'
            converted_lines.append(new_line)

        elif line.strip() == "even":
            # Skip "even" lines
            continue
        else:
            converted_lines.append(line)

with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write("\n".join(converted_lines))

print(f"Done! Result saved to {OUTPUT_FILE}")
