# Code generated by Gemini

import sys
import os
import struct

def fix_ring_bin(file_path):
    if not os.path.isfile(file_path):
        print(f"File {file_path} not found.")
        return

    with open(file_path, 'rb') as f:
        data = f.read()

    # Ensure data is 16-bit aligned
    if len(data) % 2 != 0:
        print(f"Error: {file_path} size is not multiple of 2 bytes.")
        return

    # Unpack as 16-bit unsigned integers (Big-Endian)
    words = struct.unpack(f'>{len(data)//2}H', data)
    output_words = list(words)
    changed = False

    # Check for Start Marker ($0000, $0000)
    if len(output_words) < 2 or (output_words[0] != 0 or output_words[1] != 0):
        output_words = [0, 0] + output_words
        print(f"[{file_path}] Added Start Marker.")
        changed = True

    # Check for End Marker ($FFFF, $FFFF)
    if len(output_words) < 2 or (output_words[-2] != 0xFFFF or output_words[-1] != 0xFFFF):
        output_words = output_words + [0xFFFF, 0xFFFF]
        print(f"[{file_path}] Added End Marker.")
        changed = True

    if changed:
        with open(file_path, 'wb') as f:
            # Pack back to binary (Big-Endian)
            f.write(struct.pack(f'>{len(output_words)}H', *output_words))
    else:
        print(f"[{file_path}] Markers are already present.")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python code.py 1.unc 2.unc 3.unc ...")
    else:
        for arg in sys.argv[1:]:
            fix_ring_bin(arg)
