# Code generated by Gemini

import os
import struct

def fix_ring_bin(file_path, filename):
	with open(file_path, 'rb') as f:
		data = f.read()

	if len(data) % 2 != 0:
		print(f"Error: {filename} size is not a multiple of 2 bytes.")
		return

	words = struct.unpack(f'>{len(data)//2}H', data)
	output_words = list(words)
	changed = False

	# Check for Start Marker ($0000, $0000)
	# If only one $0000 exists at the start, remove it to avoid duplicates
	if len(output_words) > 0 and output_words[0] == 0:
		if len(output_words) > 1 and output_words[1] == 0:
			pass # Valid 4-byte start marker present
		else:
			output_words.pop(0) # Remove the broken 2-byte marker
			output_words = [0, 0] + output_words
			print(f"[{filename}] Fixed incomplete Start Marker.")
			changed = True
	else:
		if len(output_words) < 2 or (output_words[0] != 0 or output_words[1] != 0):
			output_words = [0, 0] + output_words
			print(f"[{filename}] Added Start Marker.")
			changed = True

	# Check for End Marker ($FFFF, $FFFF)
	# If only one $FFFF exists at the very end, remove it first
	if len(output_words) > 0 and output_words[-1] == 0xFFFF:
		if len(output_words) > 1 and output_words[-2] == 0xFFFF:
			pass # Valid 4-byte end marker present
		else:
			output_words.pop() # Remove the broken 2-byte marker
			output_words = output_words + [0xFFFF, 0xFFFF]
			print(f"[{filename}] Fixed incomplete End Marker.")
			changed = True
	else:
		if len(output_words) < 2 or (output_words[-2] != 0xFFFF or output_words[-1] != 0xFFFF):
			output_words = output_words + [0xFFFF, 0xFFFF]
			print(f"[{filename}] Added End Marker.")
			changed = True

	if changed:
		with open(file_path, 'wb') as f:
			f.write(struct.pack(f'>{len(output_words)}H', *output_words))
	else:
		print(f"[{filename}] Markers are already present.")

def process_all_rings():
	current_dir = os.path.dirname(os.path.abspath(__file__))

	files = [f for f in os.listdir(current_dir) if f.lower().endswith('.unc')]

	if not files:
		print("No .unc files found for Ring processing.")
		return

	for filename in files:
		filepath = os.path.join(current_dir, filename)
		fix_ring_bin(filepath, filename)

if __name__ == "__main__":
	process_all_rings()
	input()
