# Code generated by LLaMA

# Get the first value from the console
value = int(input("Enter a value: "), 16)

# Get the percentage from the console
percent = int(input("Enter a percentage: "))

# Calculate the value from the percentage
result = int((value / 100) * percent)

# Print the result in hexadecimal format
print(f"Result: 0x{result:X}")