# Code generated by ChatGPT

value = int(input("Enter the value: "), 16)
percent = float(input("Enter the percentages: ").replace(",", "."))
result = value * percent / 100

result_hex = hex(int(result))
result_hex_formatted = result_hex[:2] + result_hex[2:].upper()

print(f"Result: {result_hex_formatted}")