# Code generated by Gemini

import os
import struct

def process_object_data():
	current_dir = os.path.dirname(os.path.abspath(__file__))

	files = [f for f in os.listdir(current_dir) if f.lower().endswith('.unc')]

	if not files:
		print("No .unc files found in the directory.")
		return

	for filename in files:
		filepath = os.path.join(current_dir, filename)

		with open(filepath, 'rb') as f:
			file_data = f.read()

		file_len = len(file_data)
		if file_len < 6:
			print(f"Skipped (File too small): {filename}")
			continue

		is_6_bytes = (file_len % 6 == 0)
		is_8_bytes = (file_len % 8 == 0)

		# If it doesn't fit any valid layout perfectly, it's corrupted or manually modified
		if not is_6_bytes and not is_8_bytes:
			print(f"Error: File size ({file_len} bytes) is corrupted or sub-aligned: {filename}")
			continue

		# Handle ambiguous sizes (e.g., 24, 48, 96 bytes) by checking pointers
		if is_6_bytes and is_8_bytes:
			if file_data[6:8] == b'\xFF\xFF' or file_data[8:10] == b'\xFF\xFF':
				is_6_bytes = False
			else:
				is_8_bytes = False

		new_data = bytearray()
		file_changed = False

		# --- Case 1: Convert 6-byte format to 8-byte format ---
		if is_6_bytes:
			for offset in range(0, file_len, 6):
				block = file_data[offset:offset+6]
				if len(block) < 6:
					break

				xpos, y_flags, obj_id, subtype = struct.unpack('>HHBB', block)

				if xpos == 0xFFFF:
					new_data.extend(struct.pack('>HHHH', 0xFFFF, 0, 0, 0))
					file_changed = True
					break

				flags = y_flags & 0xF000
				clean_y = y_flags & 0x0FFF
				new_id = obj_id | flags

				new_data.extend(struct.pack('>HHHH', xpos, clean_y, new_id, subtype))
				file_changed = True

			if file_changed:
				print(f"Converted 6B -> 8B: {filename}")

		# --- Case 2: Fix flags in an already existing 8-byte format ---
		elif is_8_bytes:
			for offset in range(0, file_len, 8):
				block = file_data[offset:offset+8]
				if len(block) < 8:
					break

				xpos, y_flags, obj_id_flags, subtype = struct.unpack('>HHHH', block)

				if xpos == 0xFFFF:
					new_data.extend(struct.pack('>HHHH', 0xFFFF, 0, 0, 0))
					break

				if (y_flags & 0xF000) != 0:
					flags = y_flags & 0xF000
					clean_y = y_flags & 0x0FFF

					clean_id = obj_id_flags & 0x0FFF
					new_id = clean_id | flags

					new_data.extend(struct.pack('>HHHH', xpos, clean_y, new_id, subtype))
					file_changed = True
				else:
					new_data.extend(block)

			if file_changed:
				print(f"Fixed trapped flags in 8B file: {filename}")

		if file_changed and len(new_data) > 0:
			with open(filepath, 'wb') as f:
				f.write(new_data)
		else:
			print(f"Skipped (no changes needed): {filename}")

if __name__ == "__main__":
	process_object_data()
	input()
