# Code generated by Gemini

import struct
import sys
import os

def convert_file(filepath):
    if not os.path.exists(filepath):
        print(f"Error: File {filepath} not found.")
        return

    try:
        with open(filepath, 'rb') as f:
            old_data = f.read()

        new_data = bytearray()
        
        # Step: 6 bytes (x:2, y:2, id:1, sub:1)
        for i in range(0, len(old_data), 6):
            block = old_data[i:i+6]
            
            if len(block) < 6:
                break
                
            # Unpack old format (Big Endian)
            xpos, ypos, obj_id, subtype = struct.unpack('>HHBB', block)
            
            # Terminator check ($FFFF in X)
            if xpos == 0xFFFF:
                # Expand terminator to 8 bytes: FF FF 00 00 00 00 00 00
                new_data.extend(struct.pack('>HHHH', 0xFFFF, 0, 0, 0))
                break
                
            # Pack into new format: 4 words (8 bytes)
            new_data.extend(struct.pack('>HHHH', xpos, ypos, obj_id, subtype))

        with open(filepath, 'wb') as f:
            f.write(new_data)
        
        print(f"Successfully converted: {filepath}")

    except Exception as e:
        print(f"Failed to convert {filepath}: {e}")

if __name__ == "__main__":
    # Get all arguments after the script name
    files = sys.argv[1:]
    
    if not files:
        print("Usage: python code.py file1.bin file2.bin file3.bin ...")
        sys.exit(1)

    for file_path in files:
        convert_file(file_path)

    print("\nBatch conversion complete.")
